#ddev-generated
services:
  kibana:
    container_name: ddev-${DDEV_SITENAME}-kibana
    image: kibana:8.13.4
    restart: "no"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=5600:5601
      - HTTPS_EXPOSE=5601:5601
      - ELASTICSEARCH_HOSTS=https://ddev-${DDEV_PROJECT}-elasticsearch:9201
    depends_on:
      - elasticsearch

  # Set the necessary environment variables to access the Elasticsearch API.
  elasticsearch:
    environment:
      - http.cors.enabled=true
      - "http.cors.allow-origin=*"
